import type { PolicyConfig } from "./types.js";

export { actionRiskLevels } from "../action-catalog.js";

export const deniedActionPatterns = [
  /erase_disk/i,
  /format_drive/i,
  /modify_system_usb_permissions_without_approval/i,
  /curl_pipe_to_shell/i,
  /delete_home_directory/i,
  /run_unbounded_shell_loop/i,
];

export const defaultPolicy: PolicyConfig = {
  approval_required: [
    "upload_firmware",
    "upload_filesystem",
    "agent_flash_monitor_verify",
    "erase_flash",
    "reset_server_state",
    "run_shell_command",
    "ssh_deploy",
  ],
  allow: [
    "list_devices",
    "list_boards",
    "get_board_info",
    "get_project_config",
    "get_policy_status",
    "get_monitor_status",
    "list_task_history",
    "get_approval_request",
    "list_pending_approvals",
    "agent_resolve_target",
    "build_project",
    "check_project",
    "query_logs",
    "start_monitor",
    "stop_monitor",
    "capture_serial_window",
    "agent_monitor_health",
    "cancel_task",
    "agent_validate_project",
    "agent_build_diagnose",
    "agent_safe_pin_audit",
    "agent_get_last_report",
    "agent_generate_board_report",
    "get_project_context",
    "get_lock_status",
    "search_libraries",
    "list_installed_libraries",
    "system_info",
    "get_dashboard_url",
    "acquire_lock",
    "release_lock",
    "init_project",
    "clean_project",
    "install_library",
    "uninstall_library",
    "update_library",
  ],
  deny: [
    "erase_disk",
    "format_drive",
    "modify_system_usb_permissions_without_approval",
    "curl_pipe_to_shell",
    "delete_home_directory",
    "run_unbounded_shell_loop",
  ],
  require_workspace_boundary: true,
  require_device_lock_for_upload: true,
  redact_secrets_from_logs: true,
  audit_all_agent_actions: true,
};
